### ISSUE TITLE
Color logging

### ISSUE THREAD

**Issue by cup** [abseil/abseil-py#104]
I can create this file:

~~~py
from absl import logging
logging._warn_preinit_stderr = 0
logging.warning('Worrying Stuff')
~~~

but it outputs in black and white. Is color an option?

**Comment by gpshead** [comment]
We're have no plans to detecting terminals and adding ansi color codes to terminal based log output ourselves, sorry.

Perhaps look into whether https://pypi.org/project/coloredlogs/ or something similar would do what you desire.

**Comment by cup** [comment]
@gpshead thanks that is a good one - also these seem to do the job

- https://github.com/metachris/logzero
- https://github.com/borntyping/python-colorlog
