### ISSUE TITLE
How to remove extra flags?

### ISSUE THREAD

**Issue by Rogersjk** [abseil/abseil-py#106]
When I call FLAGS.flag_values_dict(), I want to get the dict of defined hyper parameters, 
but I find there have been some parameters such as "run_with_pdb", "verbosity" and so on.

Is there a method that can return the dict items which only contain parameters that I define in my code?

**Comment by gpshead** [comment]
I don't believe we have an API for that specifically but you might be able to construct what you want by filtering using information from `FLAGS.key_flags_by_module_dict()` or `FLAGS.get_key_flags_for_module()` which are not the same thing but should let you figure out what came from where.

**Comment by Rogersjk** [comment]
> I don't believe we have an API for that specifically but you might be able to construct what you want by filtering using information from `FLAGS.key_flags_by_module_dict()` or `FLAGS.get_key_flags_for_module()` which are not the same thing but should let you figure out what came from where.

Many thanks, FLAGS.get_key_flags_for_module solves my problem:
  flags_dict = dict((item.name, item.value) for item in FLAGS.get_key_flags_for_module(sys.argv[0]))
In this way, I can get the dict items of FLAGS with only values that I defined in my code.

**Comment by gpshead** [comment]
Great!  I'm going to close this, as that's a single comprehension that does what you need. :)
