### ISSUE TITLE
Is it possible to use ABSL flags in a child process?

### ISSUE THREAD

**Issue by RodrigoMorimoto** [abseil/abseil-py#107]
I am trying to use the FLAGS values on a application which uses multiple process (python multiprocess lib) with pipe objects, but, when I try to access those values on a child process I get the error `absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --tracking before flags were parsed  `.
I think that I am getting this error because when I try to spawn a new process, it not run the app.run() function again on each function that is called by ` b_proc = Process(target=modes, args=[receiver])`
Is there a way to solve it without the need to parse each FLAG value to a list and pass it to the child process as a argument?

code Example:
```

import multiprocessing as mp
from multiprocessing import Pool, Process, Value, Array
from absl import app, flags, logging
from absl.flags import FLAGS

flags.DEFINE_boolean('tracking', False, 'new tracking')

def modes(detection):
    print('start streaming')
    print(type(detection))
    FLAGS = flags.FLAGS
    if FLAGS.tracking:
        time.sleep(10)
        track=get_track(detection)
        np.savetxt("my_track.txt", track, newline="\n")
    else:
        streaming(detection)


def main(argv):
    receiver , sender = mp.Pipe()
    b_proc = Process(target=modes, args=[receiver])

if __name__ == "__main__":
    try:
        app.run(main)
    except SystemExit:
        pass



```

**Comment by gpshead** [comment]
Within Google the use of `multiprocessing` is rare as it doesn't work in our environment for a variety of reasons not worth getting into here.  But what this does mean is that we haven't designed absl with that in mind.

What it'd take for it to work with `multiprocessing` using the safe `spawn` method of child process creation would be a way for such spawned children to get their own copy of the global FLAGS containing the same values.

At a quick glance, you can _probably_ do this without too much effort via `FLAGS.append_flags_into_file()` on the parent process side and `FLAGS.read_flags_from_files('--flagfile=path/to/said/file')` + `.mark_as_parsed()` in the child process before using FLAGS.

**Comment by RodrigoMorimoto** [comment]
It work like a charm! thank you :)

**Comment by haohang96** [comment]
How you figure out this problem, Can you post detailed code？ Thanks！
