### ISSUE TITLE
ISO 8601

### ISSUE THREAD

**Issue by bh9** [abseil/abseil-py#110]
Formatting as ISO 8601 would be nice
https://en.wikipedia.org/wiki/ISO_8601
It should be as simple as adjusting
https://github.com/abseil/abseil-py/blob/9d73fdaa23a6b6726aa5731390f388c0c6250ee5/absl/logging/__init__.py#L659-L670
to follow the standard e.g.
```
return '%04d-%02d-%02dT%02d:%02d:%02d.%06d %c %5d %s:%d] %s' % (
    created_tuple.tm_year,
    created_tuple.tm_mon,
    created_tuple.tm_mday,
    created_tuple.tm_hour,
    created_tuple.tm_min,
    created_tuple.tm_sec,
    created_microsecond,
    severity,
    _get_thread_id(),
    record.filename,
    record.lineno,
    critical_prefix)
```

**Comment by gpshead** [comment]
The absl log line format is the Google log line format chosen probably close to 20 years ago at this point for its brevity, relevance, and ease of understanding by humans. We're not going to add alternate formats unless C++ abseil adds alternate formats.

**Comment by bh9** [comment]
abseil-cpp does support alternate formats, including one that follows 8601 https://github.com/abseil/abseil-cpp/blob/c6c3c1b498e4ee939b24be59cae29d59c3863be8/absl/time/time.h#L1190-L1193

**Comment by yilei** [comment]
Oops, the C++ abseil @gpshead's referring to is the `logging` library, which hasn't been released yet.

That link is the C++ `absl/time` library, which is not related to logging formats.

If you need a custom logging format, you can always create your own `logging.Formatter` subclass, and call `absl.logging.get_absl_handler().setFormatter(my_formatter)`.
