### ISSUE TITLE
How to log to file same time with stderr 

### ISSUE THREAD

**Issue by zh794390558** [abseil/abseil-py#111]

**Comment by yilei** [comment]
You can call `absl.logging.get_absl_handler().use_absl_log_file()` to log to file.

Then you can specify the flag `--alsologtostderr` to also log to stderr.

There is a separate `--stderrthreshold` flag and `absl.logging.set_stderrthreshold` function to control what levels of log go to stderr.

Hope this helps.

**Comment by zh794390558** [comment]
Thanks.
