### ISSUE TITLE
logging into file 

### ISSUE THREAD

**Issue by cookingbear** [abseil/abseil-py#136]
Hi:
I follow the instructions as 
#117.
It does not work. the file was created but was empty even my code is same as #117 :

import os
import absl
from absl import logging
if not os.path.exists('./'):
   os.makedirs('./')
logging.get_absl_handler().use_absl_log_file('absl_logging', './')
absl.flags.FLAGS.mark_as_parsed()
logging.set_verbosity(logging.INFO)
logging.info('test')

**Comment by yilei** [comment]
As said in https://github.com/abseil/abseil-py/issues/117#issuecomment-545761750, you need to put your code in the main function called by`app.run(main)`:

```
from absl import app
from absl import logging

def main(argv):
  del argv  # Unused
  logging.get_absl_handler().use_absl_log_file('absl_logging', 'some dir')
  logging.info('test')

if __name__ == '__main__':
  app.run(main)

**Comment by fuhailin** [comment]
How to set absl log file  and print to the screen meanwhile?

**Comment by yilei** [comment]
Looks like you already found the answer (`--alsologtostderr`) at https://github.com/abseil/abseil-py/issues/83#issuecomment-614008919.

**Comment by yilei** [comment]
Closing assuming you found the answer. Feel free to reopen if you still have questions.
