### ISSUE TITLE
Add year to log line

### ISSUE THREAD

**Issue by kgreenek** [abseil/abseil-py#139]
glog recently added the year to the log line. I think abeil-py should too for compatibility. It's also useful to have the year, and only adds 4 characters.

This log line:
```
I0308 23:47:32.089828 400441 config.cc:27] Some log message
```

Would change to this:
```
I20200308 23:47:32.089828 400441 config.cc:27] Some log message
```

Issue:
https://github.com/google/glog/issues/516

PR:
https://github.com/google/glog/pull/530

**Comment by gpshead** [comment]
We're unlikely to do this.  That google/glog project is mostly unrelated to our actual internal C++ logging library other than being derived from a very old version of it and thus having a mostly compatible C++ API.

abseil-cpp may gain a logging library in the future; we aim keep abseil-py in sync with the internal logging library behavior and anything abseil-cpp does.

Changing the log line format is unlikely for compatibility reasons.

**Comment by kgreenek** [comment]
+1 for abeil-cpp open-sourcing the logging library.

Now it looks like our c++ glog logs will be different from our python absl-py logs if we update glog.
