### ISSUE TITLE
logging messages written out as stderr

### ISSUE THREAD

**Issue by tarrade** [abseil/abseil-py#141]
This is probably a trivial question/observation but is it expected that logging messages are written out as stderr ? Couldn't find anything in the documentation. Is this expected ?

Here a basic example (from an notebook):
![image](https://user-images.githubusercontent.com/12021701/81843136-77041c80-954d-11ea-91e9-c5953cb944f8.png)
The output with the red background is STDERR. A standard python print is STDOUT. The same things is observed here:

```
$ python test.py
I0513 19:15:53.300433 4727559616 test.py:20] test
this is another test
I0513 19:15:53.300617 4727559616 test.py:22] test
W0513 19:15:53.300679 4727559616 test.py:23] test
E0513 19:15:53.300729 4727559616 test.py:24] test
$ python test.py > file
I0513 19:16:05.292232 4569572800 test.py:20] test
I0513 19:16:05.292389 4569572800 test.py:22] test
W0513 19:16:05.292447 4569572800 test.py:23] test
E0513 19:16:05.292515 4569572800 test.py:24] test
```
How can redirect the logging messages as stdout ? Using it with Tensorflow on GoogleCloudPlatform with Stackdriver makes all output from the logging as error messages.

Using `logging.set_stderrthreshold(logging.INFO)` doesn't seems to have any impact. I am using `absl-py 0.9.0`

**Comment by yilei** [comment]
This is the standard behavior and what Python's standard `logging` module does.

If you want stdout, you can configure using [`logging.basicConfig(stream=sys.stdout... and other options)`](https://docs.python.org/3/library/logging.html#logging.basicConfig) **before** you call `absl.app.run` or whatever Tensorflow's main function. This way you have the complete control how it logs and `absl.logging` won't use its own handlers.

Or you can call `absl.logging.get_absl_handler().python_handler.stream = sys.stdout` to override the stream.

**Comment by tarrade** [comment]
Perfect, work like a charm. Thanks for all these info
