### ISSUE TITLE
Incorret flags.DEFINE_boolean() behavior 

### ISSUE THREAD

**Issue by AshiakerWang** [abseil/abseil-py#143]
### **demo python script**
```
from absl import app
from absl import flags
FLAGS = flags.FLAGS
flags.DEFINE_boolean('tea',True,'Soggy Leaves')
def test(unused_argv):
   if FLAGS.tea:
        print( "have some tea" )
   else:
        print( "no tea" )
if __name__ == '__main__':
   app.run(test)
```

The following output is **expected** while executing `python test2.py --tea False` in the command line
-  `no tea`

However, the **actual** output while executing `python test2.py --tea False` is 
- `have some tea`
 
**In other words**, no matter which boolean argument(i.e. True or False) is set in the command line, the output of the demo python script remains unchanged.

**Comment by AshiakerWang** [comment]
![TIM截图20200527225444](https://user-images.githubusercontent.com/14258909/83036391-21f7f880-a06d-11ea-9308-e0b3a9d76875.png)
 Here is a screenshot of my code running results.

**Comment by gpshead** [comment]
boolean flags do not take an additional argument.  `--tea` means True.  `--notea` means False.  `--tea=True` and `--tea=False` and related true/false values after = also work.

**Comment by AshiakerWang** [comment]
Thanks for your explanation!
