### ISSUE TITLE
Orthographic errors around code

### ISSUE THREAD

**Issue by mkfilipiuk** [abseil/abseil-py#151]
Hi all,

I've spotted that there are a few orthographic errors regarding spelling of the word `helpful`; in the code you can find `helpfull` in several places: https://github.com/abseil/abseil-py/search?q=helpfull&unscoped_q=helpfull

Shall I make a PR to fix it to `helpful`?

Best,
Michał Filipiuk

**Comment by yilei** [comment]
Thanks, I can see why this is confusing but it is not a typo. It means `help`-`full`, as you can see there is another flag `help`-`short`, they produce `full` and `short` help messages. Hope this clarifies.
