### ISSUE TITLE
PIP install failing on MACOS

### ISSUE THREAD

**Issue by wolfiex** [abseil/abseil-py#163]
Py3 virtual environment set by conda (as seen in the error message)

```
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/Users/xxxxx/miniconda2/envs/py3/lib/python3.6/site-packages/absl_py-0.11.0.dist-info/METADATA'
```

**Comment by yilei** [comment]
This might be caused by previous incomplete installations where `absl_py-0.11.0.dist-info/*` exists but somehow the `absl_py-0.11.0.dist-info/METADATA` file is missing.

Try deleting the entire `absl_py-0.11.0.dist-info` directory and `pip install absl-py` again.

**Comment by wolfiex** [comment]
It seemed that upgrading the python version fixed the issue.
