### ISSUE TITLE
getting the dict version of FLAGS

### ISSUE THREAD

**Issue by IssamLaradji** [abseil/abseil-py#164]
Thanks for this great repo. Could you help met the `dict` version of `FlagValues` so I could have a global view of the (key, value) pairs of the object?

**Comment by yilei** [comment]
`FLAGS.flag_values_dict()` returns a `dict` of `{flag key: flag value}`, does this work for you?

**Comment by IssamLaradji** [comment]
Yep, it did! thanks @yilei !
