### ISSUE TITLE
Python 2 EOL

### ISSUE THREAD

**Issue by gitpushdashf** [abseil/abseil-py#169]
When would be a good time to remove Python 2 support? It's been EOLed for a while.

Thank you!

**Comment by yilei** [comment]
Yes, we plan to remove Python 2 support in the next release (likely versioned as 1.0.0).

**Comment by gitpushdashf** [comment]
Sounds good, thank you!

**Comment by yilei** [comment]
v1.0.0 has dropped Python 2 support.

**Comment by gitpushdashf** [comment]
Great, thank you!

**Comment by gitpushdashf** [comment]
Is `six` still necessary with Python 2 support removed?

**Comment by yilei** [comment]
These will be cleaned up in future updates. Also internally we have a few very rare cases that still use parts of the library in Python 2, those will need cleanups too.
