### ISSUE TITLE
absltest doesn't set up test filtering and fail fast correctly when argv= is explicitly passed to absltest.main

### ISSUE THREAD

**Issue by bhack** [abseil/abseil-py#173]
Mentioning @yilei from https://github.com/abseil/abseil-py/issues/128#issuecomment-921993484:
> I currently think it makes sense for absltest to merge the updated argv with the user specified one from kwargs,

/cc @haifeng-jin

**Comment by yilei** [comment]
Correction from https://github.com/abseil/abseil-py/issues/128#issuecomment-922025423:

> Ah, since kwargs['argv'] always overrides argv in _run_and_get_tests_result, we should add filtering flags to kwargs['argv'] if present.
