### ISSUE TITLE
avoid DuplicateFlagError during debugging

### ISSUE THREAD

**Issue by shankyemcee** [abseil/abseil-py#192]
I would like to debug my code which uses flags but I get the error: 

DuplicateFlagError: The flag 'workdir' is defined twice.

I understand from other posts that for python modules the flags get loaded twice. How can I debug my code to avoid these errors?

I am using python 3.10 on windows and debugging on spyder ide.

Thanks

**Comment by yilei** [comment]
Do you have a full traceback and error message? It should contain the two places where this flag is defined.

I'm not familiar with spyder, does it re-import your modules twice during your debugging process? `absl.flags` should be handling the "module being re-imported / re-loaded" case here: https://github.com/abseil/abseil-py/blob/58ead8c22230a2493006fa0ab9f76776b6e7280f/absl/flags/_flagvalues.py#L423-L428

**Comment by shankyemcee** [comment]
This is the error it produces:

absl.flags._exceptions.DuplicateFlagError: The flag 'workdir' is defined twice. First from c:\users\dell g7 user 2\documents\projects\vision_transformer\vision_transformer\vit_jax\main.py, Second from c:\users\dell g7 user 2\documents\projects\vision_transformer\vision_transformer\vit_jax\main.py.  Description from first occurrence: Directory to store logs and model data.

The code that runs:


      
FLAGS = flags.FLAGS

_WORKDIR = flags.DEFINE_string('workdir', 'workdir','Directory to store logs and model data.')


This is the code that came with the script. It is supposed to be a python module and was not meant to be run iteratively, hence the odd behavior.

**Comment by yilei** [comment]
Looks like when you rerun the module in spyder, it will re-execute the module a second time without actually starting a new process.

From `absl.flags`'s perspective, this is really working as intended: it defines the `--workdir` flag in the _global_ `FLAGS` object the first time your run the script. Then in the second run, it tries to define the flag _again_ in `FLAGS` with the same module object.

I think you'll get better answers from spyder users/community.
