### ISSUE TITLE
Absl installation problem

### ISSUE THREAD

**Issue by alberto-atk** [abseil/abseil-py#218]
Hi!
I have installed all dependencies in the flare_remover app and i have a problem when i run the command.
The enviroment that i'm using:
![image](https://user-images.githubusercontent.com/73551392/227971907-7dbf7967-41c0-4b6e-9c7c-d1f1e07a261f.png)
The problem that i get:
![image](https://user-images.githubusercontent.com/73551392/227971980-edb1810d-84a8-4981-9114-b302cef2de3c.png)
Thank you!!

**Comment by yilei** [comment]
Make sure absl-py is really installed, by running `python3 -c 'from absl import app'`.

Other than this, it doesn't seem to be an issue we can help with on the absl side. Try flare_remover's?

**Comment by alberto-atk** [comment]
I'm still getting the error
![image](https://user-images.githubusercontent.com/73551392/227980180-ff384524-6255-4a4e-9534-b73c7cdd4401.png)
And in pip appears that absl is installed

**Comment by yilei** [comment]
What about `python3 -m pip list`?

**Comment by alberto-atk** [comment]
![image](https://user-images.githubusercontent.com/73551392/227989845-184ef12c-375f-4b92-9d83-02b8e131544a.png)
This is the output, previously i had this one and i updated pip
![image](https://user-images.githubusercontent.com/73551392/227990025-b2c8687c-eeb9-462c-b058-1920bafae497.png)

**Comment by yilei** [comment]
Yeah your `pip` and `python3` are using different Python installations. And you don't have absl-py (and anything else installed) for whatever `python3` points to. You can try `pip3` or `python3 -m pip` whenever you used `pip`.

**Comment by alberto-atk** [comment]
Thank you so much
That was the problem!!
