### ISSUE TITLE
If I use use_absl_log_file, I will get two files with the same content, what can I do to generate just one file?

### ISSUE THREAD

**Issue by huang-zi-jian** [abseil/abseil-py#220]
thank you!

**Comment by yilei** [comment]
One file, with the timestamps, is the actual log file. The other, without the timestamps, is a convenience symlink to the former. It has a predictable filename so it can be useful. The symlink will also be overridden if you run the program twice. And this behavior isn't customizable.

Hope this helps.

**Comment by yilei** [comment]
Closing, assuming this was answered. Feel free to reopen if you have more questions.
