### ISSUE TITLE
Permission issue for 1.4.0

### ISSUE THREAD

**Issue by mimaomao** [abseil/abseil-py#224]
It seems release 1.4.0 have different permission for file `PKG-INFO` with previous releases. See [here](https://bugs.archlinux.org/task/77988) for more details.

**Comment by yilei** [comment]
This doesn't seem to be an `absl-py`'s own issue.

https://bugs.archlinux.org/task/77988 is duplicated to https://bugs.archlinux.org/task/77983, which is already marked as fixed.
