### ISSUE TITLE
class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache): TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by MDENDAN** [abseil/abseil-py#277]
I install tensorflow=1.14 along with cudatoolkit=10.0 in a new conda environment. on installing and restarting the system I tried to import tensorflow but I got err from:
 abls\flags\_argument_parser.py
 class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

I checked th version of absl-py it is 2.0.0
What can be done?

**Comment by yilei** [comment]
Which Python version are you using? It can be an error in Python 3.6 or earlier, and `absl-py` 2.0.0 has dropped support for Python 3.6.

**Comment by yilei** [comment]
You'll either need to use newer Python versions or downgrade `absl-py` to pre `2.0.0`.
