### ISSUE TITLE
Failure to load archive @six_archive when loading from abseil-py from a Bazel project.

### ISSUE THREAD

**Issue by mrdmnd** [abseil/abseil-py#37]
I have added abseil-py to my project's bazel WORKSPACE like so:
```
http_archive(
    name = "io_abseil_py",
    strip_prefix = "abseil-py-master",
    url = "https://github.com/abseil/abseil-py/archive/master.zip",
)
```

I attempted to add absl:app in my build file as a dependency for a trivial python script like so:
```
py_binary(
    name = "abseil_test",
    srcs = ["abseil_test_script.py"],
    deps = ["@io_abseil_py//absl:app"],
)
```

The build fails with this message:
```
[mrdmnd@maximumkappa policygen]$ bazel clean
(05:27:48) INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
[mrdmnd@maximumkappa policygen]$ bazel build learn:abseil_test 
(05:27:52) INFO: Current date is 2018-02-27
(05:27:53) ERROR: /home/mrdmnd/.cache/bazel/_bazel_mrdmnd/c741fceeeed6ca1106cd8d8a1f1c8dbf/external/io_abseil_py/absl/flags/BUILD:5:1: no such package '@six_archive//': The repository could not be resolved and referenced by '@io_abseil_py//absl/flags:flags'
(05:27:53) ERROR: Analysis of target '//learn:abseil_test' failed; build aborted: no such package '@six_archive//': The repository could not be resolved
(05:27:53) INFO: Elapsed time: 0.993s
(05:27:53) FAILED: Build did NOT complete successfully (17 packages loaded)
[mrdmnd@maximumkappa policygen]$ 
```
I suspect that there is an issue with the provided @six_archive in your WORKSPACE file. 
Alternatively, and possibly more likely, I may have made a trivial mistake somewhere.

**Comment by yilei** [comment]
Note that transitive dependencies in WORKSPACE files are not read by bazel, see more information [here](https://docs.bazel.build/versions/master/external.html#transitive-dependencies).

So you need to add the six_archive in *your own* `WORKSPACE` file:

```python
new_http_archive(
    name = "six_archive",
    urls = [
        "http://mirror.bazel.build/pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz",
        "https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz",
    ],
    sha256 = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a",
    strip_prefix = "six-1.10.0",
    build_file = "third_party/six.BUILD",
)
```

Let me know if this solves your issue.

**Comment by mrdmnd** [comment]
Yep, this solves it. Thanks.

**Comment by hhmitchell** [comment]
Should this work as-is?  build_file = "third_party/six.BUILD" doesn't exist in the six archive, only in abseil-py.  I had to manually copy the contents of six.BUILD as found in abseil-py into build_file_content, not build_file.

Was there something I'm missing?

**Comment by rickeylev** [comment]
Hm, I suspect this might have to do with a recent bazel release (0.20) that deprecated new_http_archive. I've opened a separate issue for that: https://github.com/abseil/abseil-py/issues/86
