### ISSUE TITLE
How should I run bazel tests ?

### ISSUE THREAD

**Issue by eLvErDe** [abseil/abseil-py#40]
Hi there,

I added the WORKSPACE file from GitHub into the package published on pypi, but when I run
```
bazel test absl
```

It says:
```
ERROR: no targets found beneath 'absl'.
INFO: Elapsed time: 0.105s
ERROR: Couldn't start the build. Unable to run tests.
```

Thanks

**Comment by yilei** [comment]
Hi,

The package published on PyPI doesn't include tests nor bazel BUILD files. If you are interested in running tests, you can clone the repo then run `bazel`:

```bash
git clone git@github.com:abseil/abseil-py.git
cd abseil-py
bazel test absl/...
```

I'll update the README.md files so it's more clear.

**Comment by eLvErDe** [comment]
Any reason why this is excluded from pypi release ?

**Comment by yilei** [comment]
We don't want to pollute the PyPI library with the tests, since they are not part of the API we provide. Plus, the tests require `bazel`, which isn't a thing you would run *inside* a `pip` installed directory.

**Comment by yilei** [comment]
Right now our tests aren't structured to be run without `bazel`, and we also don't want to add `bazel` as an extra dependency for things related to the PyPI distribution.

I think it's technically possible to run at least some of the tests without `bazel`, and provide them as part of PyPI test suites. But we are not there yet.

**Comment by eLvErDe** [comment]
It's fine to run them through bazel, this is only required to build the original package and provide a proof that the code it's working fine. It won't be required when installing the binary package (exactly the same as Sphinx and various "heavy" documentation system).
Anyway, could you create a GitHub tag matching pypi releases ? That would be a perfect workaround for people looking for source code along the matching test suite. Thanks

**Comment by yilei** [comment]
git-tags are indeed useful.

We'd like to create tags named like `pypi-v0.1.10`, `pypi-v0.1.11`. Would this work for you?

We want to emphasize that these are for mapping PyPI releases only, and de-emphasize the concept of versions for users who directly depend on source code. Hence the prefix `pypi-`.

**Comment by yilei** [comment]
A git-tag is created for the latest PyPI release. Future releases will also include such tags.

**Comment by jayvdb** [comment]
rpm packaging is done within a VM without internet access.

When I try testing with bazel, it attempts to fetch lots of packages from the internet.

Is there any way to use bazel without internet ?  Pre-fetching all of the dependencies and including them in the rpm SOURCES?

**Comment by rickeylev** [comment]
Hi John,

Please open a separate issue to discuss that

>
