### ISSUE TITLE
flags, required flag?

### ISSUE THREAD

**Issue by Artanicus** [abseil/abseil-py#42]
I must be missing something but I'm not finding any way to mark a flag as being required? Or is it an intentional design choice to not support that?

**Comment by yilei** [comment]
This can be done via [validators](https://github.com/abseil/abseil-py/blob/ea5c2fae775adce9a41af69d8d48f48d235e5bb7/absl/flags/_validators.py#L17), and there is a built-in `mark_flag_as_required` function to achieve that.

Usually, to make a flag required, first make sure the default value is `None`, then call `flags.mark_flag_as_required('flag_name')` before parsing flags. Example:

```python
from absl import app
from absl import flags

flags.DEFINE_string('fruit', None, 'The fruit to eat.')

def main(argv):
    # ...

if __name__ == '__main__':
    flags.mark_flag_as_required('fruit')
    app.run(main)
```

`mark_flag_as_required` makes sure the flag's value is not `None` after flags are parsed.

**Comment by Artanicus** [comment]
That works, thanks! For the life of me couldn't find it based on docstrings, hopefully the upcoming documentation will make this easier.
