### ISSUE TITLE
Is it possible to save flagfiles?

### ISSUE THREAD

**Issue by vlad17** [abseil/abseil-py#57]
I asked this question [on SO](https://stackoverflow.com/questions/50202755/whats-the-idiomatic-way-of-performing-conversions-from-python-gflags-to-yaml-an) but it seems there are not enough people using this flag library there to answer it (or there may be no good answer).

Given an invocation of some python application using gflags, which may or may not rely on flag files, e.g., `python myapp.py --flagfile someflagfile.txt --some_other_flag x`, it is very useful to be able to recover the structured configuration of the invocation (for instance, I'm performing experiments and would like to record the configuration used to perform the experiment in JSON along with the experiment logs).

My current solution is the following manual one, but I was hoping there was a better way of doing it

```
from absl import flags
d = flags.FLAGS.flags_by_module_dict()
d = {k: {v.name: v.value for v in vs} for k, vs in d.items()}
```

The only issue with the above is that if I say, print out the dict `d` as JSON, I can't feed it back in as a `--flagfile` again.

**Comment by yilei** [comment]
`FLAGS. flags_into_string()` should return a string that can be put in a flagfile. Or `FLAGS. append_flags_into_file('path/to/flagfile.txt')` will append the flags to that file.

Does this work for you?

**Comment by vlad17** [comment]
That's exactly it, thanks.

**Comment by ataiya** [comment]
Is there a way to only get the "key" flags to be outputted by FLAGS.flags_into_string()?
i.e. the ones documented by --helpshort

**Comment by rickeylev** [comment]
I think something like this would do it:

```
key_flags = FLAGS.get_key_flags_for_module(...)
'\n'.join(f.serialize() for f in key_flags)
```
That'll do almost the same thing. To call flags_into_string with a custom set of flags defined, you'll have to create a flags.FlagsValue() object, then populate it with the flags you want. I think something like this:

```
fv = flags.FlagsValues()
for f in ..get key flags...:
  setattr(fv, f.name, f.value)
fv.flags_into_string()
```

Though I have to ask: what is it, you're trying to do, exactly?
(also, lets open a new issue to continue the conversation if necessary, soas not to spam the original people on this issue)

**Comment by ataiya** [comment]
I would like to "save" the options of a neural network training.
However, the FLAGS.* contains hundreds of options that I have never defined.
The --help seemed to understand the difference between the full set, and the ones that my application defined.

Makes sense?
