### ISSUE TITLE
assertSameStructure with dict vs defaultdict

### ISSUE THREAD

**Issue by EhsanKia** [abseil/abseil-py#59]
When trying to use assertSameStructure to compar a dict to a defaultdict, it throws an error.
This is due to the direct type comparison here
https://github.com/abseil/abseil-py/blob/master/absl/testing/absltest.py#L1219

Not sure if it's worth adding another exception similar to int vs long. Feel free to close if this is WAI

**Comment by rickeylev** [comment]
Thanks for the report. I'd consider it a bug. A normal dict and default dict (or ordered dict) compare equal, I don't see why the assert method should care about their types.

Looking through the change history, it doesn't look like that type check was added for a specific reason (it's been there since the beginning), so it might as well be removed.

**Comment by EhsanKia** [comment]
Dict vs OrderedDict is definitely a trickier case, especially since (at least right now) function cares about order in lists, but I think that at least for defaultdicts, it's a clearer case.

I guess speaking of removing the type check brings up other questions, such as lists vs tuples or str vs unicode, both of which would pass without the type check.

As you allude to, we need a better definition of what "structure" means in this case. In my mind, it was about higher level structure of the data such as mappings and sequences.

**Comment by EhsanKia** [comment]
I'm trying to think which way would be actually useful in the context of testing, and honestly I think they both have their use. One solution could be to have a strict_type_check=True parameter that allows the engineer to choose between the two behaviors. That also makes the function backward compatible and doesn't break existing tests.

**Comment by gpshead** [comment]
My preference is to take the most conservative route and only explicitly allow defaultdict to compare to dict if there is a compelling need.

Even allowing `collections.defaultdict` could require special case handling. The comparison code can cause new default keys to be inserted into the defaultdict.  Assertions should not have side effects (OTOH the entire point of defaultdict is to be a side effect, no idea what to make of that).  A defaultdict would need to be converted into a plain dict for purposes of comparison without side effects.

Wait until someone has a need for dict ordering to be part of the comparison and decide what to do about 3.7 dict and OrderedDict at that time.  That one may require a mode flag or new method such as your strict_type_check suggestion.  For now people think of dicts as always unordered, but that is likely to change over time thanks to 3.7's behavior.

That there are special cases needed for these already suggests that the strict type check is a good thing.  Not being strict in test comparisons can lead to unintentionally passing tests, which is worse than an unintentionally failing tests as it isn't likely to be detected.

**Comment by rickeylev** [comment]
For reference, ==, assertEqual, and assertDictEqual all ignore ordered-ness and default-ness and just treat them as plain dicts.

From what I can tell of assertSameStructure is that it doesn't care about ordering of keys. Just the ordering of sequences (which makes sense). Overall, assertSameStructure seems to be basically assertEqual, except stripped down a bit and with different error reporting. TBH, it seems like a _best_ thing to do would be to deprecate assertSameStructure and improve assertEqual's error reporting for large structures, but that's a bit pie-in-the-sky.

**Comment by gpshead** [comment]
`long` and `int` being special is not odd at all, Python 1.x's numeric types are not intended to ever be treated as separate types anymore. They auto-convert freely in Python 2 and the distinction no longer exist in Python 3.

Yes, I see what you mean, defaultdict could be supported.  I only quickly glanced at the code and saw the `a[k]` and `b[k]`.  I'd be fine with supporting defaultdict here.
