### ISSUE TITLE
Why is stack info in findCaller limited to PY3?

### ISSUE THREAD

**Issue by EhsanKia** [abseil/abseil-py#62]
In ABSLLogger.findCaller(), the documentation says:
```
stack_info: bool, when using Python 3 and True, include the stack trace as the fourth item returned instead of None.
```
https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py#L885

First off, that's a bit confusing. It makes it sounds like it'll return None if you're using PY2, but it actually returns 3-tuple, making PY2-3 compatibility messy.

The bigger question though is why? I'm not sure what part of that code isn't compatible. Python 2 has StringIO and traceback.print_stack(), so why is stack information only done in PY3?

**Comment by gpshead** [comment]
The findCaller() API comes from the CPython standard library logging
module.  In 2.7 it returns a three-tuple.  In 3.x is returns a four-tuple.
  https://github.com/python/cpython/blob/2.7/Lib/logging/__init__.py#L1240
vs https://github.com/python/cpython/blob/3.6/Lib/logging/__init__.py#L1375

The stdlib logging.Logger base class itself expects those semantics when it
calls findCaller, other code may as well.

**Comment by EhsanKia** [comment]
I see, that makes sense. Though, the PY2 version also doesn't take stack_info parameter, so if someone does pass stack_info=True, would it not be fair to return a 4-tuple, since it's fair to say it's not legacy PY2 code? Cheers.
