### ISSUE TITLE
Multi integer field does not accept tuples.

### ISSUE THREAD

**Issue by siavash-khodadadeh** [abseil/abseil-py#78]
When defining a multi-field, it should always be a list and tuple is not accepted. I would be more than happy to help with this.

**Comment by rickeylev** [comment]
Defining a multi flag should accept any iterable (this would allow people to put inline generators, dict.keys(), sets, etc), but the resulting output type should be a list for consistency. Feel free to send a PR

**Comment by siavash-khodadadeh** [comment]
@rickeylev 
I have written code and tests to fix this. Can you help me with how can I send the pull request? Should I fork the repository? or can I just gain access and push a new branch?

**Comment by gpshead** [comment]
For Github, the common workflow is to just fork the repository. It'll let you create PRs from branches on your fork on the original repo.  Something similar to the instructions in https://devguide.python.org/.

**Comment by siavash-khodadadeh** [comment]
@gpshead 
This is the first time that I am contributing to open source projects and sorry for being a newbie. I think I have sent a PR now, I am not sure if I did it correctly. Please let me know if I need to do anything else.

**Comment by siavash-khodadadeh** [comment]
Any update on this?
