### ISSUE TITLE
pip install error when old setuptools versions used

### ISSUE THREAD

**Issue by o0starshine0o** [abseil/abseil-py#79]
python 3.6.7, install tensorflow, here is log:

`Collecting absl-py>=0.1.6 (from tensorflow->-r pip_requirenents.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/fa/ef/1fa0376563b1e0495301ada8e881d88b7ebfda433f6b31f44447fe6ef795/absl-py-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in absl-py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34; python_version<='3.4' at ; python_version<='3.4'
`

**Comment by o0starshine0o** [comment]
i'm sorry , absl-py == 0.5.0 is right, absl-py == 0.6.0 appear error

**Comment by rickeylev** [comment]
What version of pip are you using (`pip --version`)? I upgraded to 0.6 and uninstalled/reinstalled and both went OK.

Can you provide the exact command line you're running?

**Comment by o0starshine0o** [comment]
python3.5.1, pip18.1
the steps i operated :

1. make a virtual environment
`python3.5 -m venv temp`

2. cd to temp and active environment
`cd temp/`
`source bin/activate`

3. upgrade pip
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python get-pip.py`

4. show the version of pyton and pip
`python -V`

> Python 3.5.1

`pip -V`

> pip 18.1 from /Users/Abelhu/Desktop/temp/lib/python3.5/site-packages/pip (python 3.5)
5. install absl-py
`pip install absl-py`



> Collecting absl-py
> Using cached https://files.pythonhosted.org/packages/fa/ef/1fa0376563b1e0495301ada8e881d88b7ebfda433f6b31f44447fe6ef795/absl-py-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: ''long_description_content_type''
      warnings.warn(msg)
    error in absl-py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34; python_version<='3.4' at ; python_version<='3.4'
    
>    ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/86/7ptlxff10831w7wkzf15mypw0000gn/T/pip-install-c038pkm_/absl-py/

**Comment by mtdeguzis** [comment]
Same issue here in RHEL 7.4
{code}
OS RHEL 7.4
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
{code}

**Comment by rickeylev** [comment]
After searching around a bit, I found some posts of similar problems and people suggested upgrading setuptools might work around this: `pip install setuptools --upgrade`

What version of setuptools are you all using?  `python -m easy_install --version`

I haven't been able to repro this yet

**Comment by mtdeguzis** [comment]
Upgrading setuptools solves the issue. However, why are you writing the python requirement this way:
```
install_requires=[
        'six',
        "enum34; python_version<='3.4'"
    ],
```

Instead of:
```
python_requires='>=3.4',
install_requires=[
        'six',
        "enum34'"
    ],
```

Is there reason for that syntax you have?

**Comment by mrmax99** [comment]
I'm hitting this on some cloud jobs where I can't directly access the setuptools versions they are using, but it's python2.

**Comment by rickeylev** [comment]
Absl's supported (and tested) python versions are 2.7 and 3.4+. The intent of that `install_requires` line is to only install enum34 for Python versions before 3.4 (since enum doesn't exist in 2.7 or earlier python versions).

I think the `python_requires` arg in setup controsl the required python version for the whole package, not the conditions a dependency should meet to be installed.

@mtdeguzis are you able to recover the setuptools version you upgraded from?

I tried installing back to setuptools v1.0, and pip install absl 0.6 still worked. I found some posts that have some other ways to have python-version-specific dependencies, but without a way to repro the issue, I can't verify whether it'll actually work or not.

**Comment by mtdeguzis** [comment]
@rickeylev yep, I am using a base RHEL 7.4 image via Docker
```
pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)
python -c 'import setuptools; print setuptools.__version__'
0.9.8

pip install setuptools --upgrade
python -c 'import setuptools; print setuptools.__version__'
40.4.3
```
That's RHEL for you...  :/ 

Ok, I see pypa does the same for pipenv: https://github.com/pypa/pipenv/blob/master/setup.py#L24

**Comment by rickeylev** [comment]
Thank you! I was able to repro with setuptools 0.9.8

repro steps:
```shell
# python --version -> 2.7.15
# pip --version -> 18.1
# easy_install --version -> 0.9.8

pip uninstall -y enum34 absl-py
pip install setuptools==0.9.8
pip install absl-py --no-cache-dir
# results in
$ pip install absl-py --no-cache-dir
Collecting absl-py
  Downloading <snip>absl-py-0.6.0.tar.gz (93kB)
    Complete output from command python setup.py egg_info:
    /home/rlevasseur/.pyenv/versions/2.7.15/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in absl-py setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-KA5Tp3/absl-py/

```
note: --no-cache-dir is necessary since it appears the cached downloads take precedence over parsing the requires string; without it, a successful install will prevent triggering the bug

**Comment by rickeylev** [comment]
So, I think the best fix is to upgrade your setuptools package.

That said, I can understand if that's problematic in some cases. I'm pretty sure I have a fix that I'll commit in the next day or so, see: https://github.com/rickeylev/abseil-py/compare/master...rickeylev:old-setuptools-bug

I've tested it with the following configurations:
 * RHEL 7.4 (Google Cloud), Python 2.7.5, pip 8.1.2, setuptools 0.9.8
 * CentOS 7 (Google Cloud), Python 2.7.5, pip 8.1.2, setuptools 0.9.8
 * Debian/Ubuntu, Python 3.6.6, pip 18.1, setuptools 40.4.3
 * Debian/Ubuntu, Python 2.7.15, pip 18.1, setuptools 0.9.8
 * Debian/Ubuntu, Python 2.7.15, pip 18.1, setuptools 40.4.3

For those following along: if you have another OS you're seeing this error with, please tell me the OS and I can see if there's a VM image available for it. Or apply the aforementioned commit and do something like the following to see if it works:

```shell
python --version
pip --version
easy_install --version
git clone https://github.com/rickeylev/abseil-py.git
cd abseil-py
python setup.py sdist
pip uninstall enum34 absl-py
pip install --no-cache-dir dist/absl-py-0.6.1.tar.gz -t /tmp/absl-out --upgrade
```

**Comment by rickeylev** [comment]
0.6.1 has been released to pypi with the fixed setup.py

**Comment by arindam31** [comment]
I upgraded pip from ver 9.0.1 to current (20.2.3) and the problem got fixed.

**To upgrade:**
`pip install -U pip`
