### ISSUE TITLE
Howto configure logging,let it support to  write logs to a file?

### ISSUE THREAD

**Issue by zg9uagfv** [abseil/abseil-py#83]

**Comment by yilei** [comment]
`use_absl_log_file` by default checks `FLAGS.log_dir`, so you can just do:

```python
from absl import app
from absl import logging

def main(argv):
    if len(argv) > 1:
        raise app.UsageError('Too many command-line arguments.')
    logging.get_absl_handler().use_absl_log_file()

if __name__ == '__main__':
    app.run(main)
```

Feel free to re-open if you still have questions.

**Comment by fuhailin** [comment]
When set absl log file, I cannot get output from the screen, how to get output information from log file and sys.stdout both?

**Comment by dthkao** [comment]
How about running with the [`--alsologtostderr` flag](https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py#L234-L236)?

**Comment by fuhailin** [comment]
> How about running with the [`--alsologtostderr` flag](https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py#L234-L236)?

Thank you very much, it works expectly
