### ISSUE TITLE
Saving only flagfiles that appear in the --helpshort list?

### ISSUE THREAD

**Issue by ataiya** [abseil/abseil-py#92]
Is there a way to only get the "key" flags to be outputted by FLAGS.flags_into_string()?
i.e. the ones documented by --helpshort

I would like to "save" the options of a neural network training. However, the FLAGS.* contains hundreds of options that I have never defined. The --help seemed to understand the difference between the full set, and the ones that my application defined.

It wold have to 2x main uses:
1. re-running the script as it was run before (this part would be fine with the existing "flags_into_string")
2. manually inspecting the file to look at the used parameter values (this is why the long list of additional flags is very fastidious)

(Transplanted discussion from #57 as per @rickeylev request)

**Comment by rickeylev** [comment]
The way --help distinguishes between your app's flags and other flags is designating flags defined by the __main__ module as "key" flags. The main module can also adopt extra flags to be marked as key (this is usually used if you're refactored flags to some common place, but still want them to show up in --help by default).

If you look at the api of `FlagsValues` (this is the class that `flags.FLAGS` is), it has a couple functions for getting flags by module names.

In my prior post the "..." were meant as place holders. Replace them with the appropriate bits of code. Here's a slightly revised version:

```
key_flags = FLAGS.get_key_flags_for_module(module_name)
'\n'.join(f.serialize() for f in key_flags)
```

I think you want `module_name` to be the string `__main__`, though I'm not 100% sure. It'll probably be that or the fully qualified name of your module.

That little `join()` loop will get you something you can save to disk that `--flagfile` will be able to read. Its basically what `flags_into_string()` does internally.

To call `flags_into_string()` with a custom set of flags defined, you'll have to create a `flags.FlagsValue()` object, then populate it with the flags you want. I think something like this:

```
fv = flags.FlagsValues()
for f in FLAGS.get_key_flags_for_module(module_name):
  fv[f.name] = f
fv.flags_into_string()
```

(This is the same as the prior posting, but assigns the flag into the FlagsValues object in a (I think) more correct way.)

Either way (join() or building a FlagsValues) should give you something you can write to disk that --flagfile will understand.

**Comment by ataiya** [comment]
I see, sorry, I interpreted the ... as a python object :)

Poking around a bit more, I found this:
https://github.com/tensorflow/models/blob/master/research/gan/progressive_gan/train_main.py

And indeed, this works as desired (while `"__main__"` would not):
```
import sys
key_flags = FLAGS.get_key_flags_for_module(sys.argv[0])
s = '\n'.join(f.serialize() for f in key_flags)
print('absl user specified flags:\n{}'.format(s))
```

**Comment by rickeylev** [comment]
Glad you found a solution!
