### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by jayvdb** [abseil/abseil-py#93]
Would you mind creating a changelog to make it easier for packagers and other users to understand what is in each release.

Currently the best we have is "Push up to 218904912" at https://github.com/abseil/abseil-py/releases/tag/pypi-v0.6.1 , or manually building a changelog from the commits

**Comment by rickeylev** [comment]
Yeah, I've been meaning to add one, but wanted to figure out if there is some standard way to do it. Namely a file format and a tool to help populate a file based on commit descriptions.

From some looking around, I found a pretty wide variety of ways people do it.

I guess I'll just pick one.
