### ISSUE TITLE
LICENSE missing from sdist

### ISSUE THREAD

**Issue by jayvdb** [abseil/abseil-py#94]
Please include the LICENSE into the sdist uploaded to PyPI.

Also, third_party is missing from the sdist, which probably means at least the tests will not work from the sdist.

**Comment by jayvdb** [comment]
Typically this is done by creating a MANIFEST.in, with rules for which files to include and which to exclude.

However I believe in the next release it can also be done by configuring setuptools a little. See [pypa/setuptools#1636](https://github.com/pypa/setuptools/issues/1636)

**Comment by rickeylev** [comment]
Just to provide an update: this is fixed, but hasn't been merged back into github. I plan to push it this week
